package br.com.test.configuration;

public enum TipoConexaoEnum {

    SICRED_BUSCAR_USUARIOS,
    SICRED_BUSCAR_PRODUTOS_AUTENTICADO,
    SICRED_BUSCAR_PRODUTOS_SEM_AUTENTICACAO,
    SICRED_BUSCAR_PRODUTOS_COM_ID,
    SICRED_CRIAR_PRODUTO,

}
